#define BROCHE_GPIO_CPONTH_IN1_PIEDS1		24
#define BROCHE_GPIO_CPONTH_IN2_PIEDS1		23
#define BROCHE_GPIO_CPONTH_IN1_PIEDS2		2
#define BROCHE_GPIO_CPONTH_IN2_PIEDS2		2
#define BROCHE_GPIO_CPONTH_IN1_PIEDS3		2
#define BROCHE_GPIO_CPONTH_IN2_PIEDS3		2
#define	BROCHE_GPIO_BUZZER			29
